### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by grimmermatt** [UCSF-TI/tipcc-web#1]
[DELETED]

**Comment by HenrikBengtsson** [comment]
> I have added the lmod line to my .bashrc [as directed](https://ucsf-ti.github.io/tipcc-web/configuration/lmod.html), but "module --version" does not return the proper output. I am wondering if I should launch into my own installation of lmod, or if this is unadvisable.

I've updated [that webpage](https://ucsf-ti.github.io/tipcc-web/configuration/lmod.html) to show Lmod 7.6 (was 7.5).  (PS. I assume that's you're seeing 7.6, but please try to give more info than "does not return the proper output" because then it's easier / quicker to give feedback).  The version of Lmod should not affect what you're experience - if you're not seeing anything at all similar to what the webpage mention then there's an error.

> I I think this is the root of pip/conda not working outside of the head node and of "module load pip" throwing an error on n6. This is also happening for user "robkylehu". Thanks.

What's the error?

**Comment by grimmermatt** [comment]
[grimmerm@n6 /]$ module --version
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/usr/share"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=undef
HAS_X11LIBS=1
LMSPLIT_SIZE=1000
MODULEPATH="/etc/modulefiles"
MODULES_INIT_DIR="/usr/share/Modules/init"
PREFIX="/usr/share/Modules"
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.7"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH=undef
WANTS_VERSIONING=0
WITH_DEBUG_INFO=undef

**Comment by HenrikBengtsson** [comment]
Wrong issue tracker, cf. https://ucsf-ti.github.io/tipcc-web/support/index.html.  I'm moving this to https://github.com/UCSF-TI/TIPCC/issues.  This issue tracker is for the website per se - not user support.

**Comment by HenrikBengtsson** [comment]
Wrong issue tracker for user help request - moved to https://github.com/UCSF-TI/TIPCC/issues
